config/routes.rb
Rails.application.routes.draw do
 
 devise_for :users,:path => "admin",:controllers => {:sessions => 'sessions',:registrations => 'users'}
    

 resources :users,:path=>"admin"
 resources :homes
 resources :gadgets
 resources :homeone

 root 'homeone#index'

namespace :api do
   namespace :v2 do
     resources :gadgets
  end
end

  

end

app/models/gadget.rb
class Gadget < ActiveRecord::Base


 CURRENCY = ['Rupee','Euros', 'Dollars', 'Pounds', 'Yeans']

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

   ROLES = ['Super Admin','Admin','NRC Reacher']
   
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/api_controller.rb
class Api::ApiController < ActionController::Base
end

app/controllers/api/v2/gadgets_controller.rb
class Api::V2::GadgetsController < Api::ApiController

	def index
    @gadgets = Gadget.search(company_name_start:params[:gadgets]).result
    render json: Project::Writer::GadgetWriter.new.write_all(@gadgets)
	end

  def show
    @gadget = Gadget.find(params[:id])
    render json: Project::Writer::GadgetWriter.new.write_show(@gadget)
	end

  def create
    puts params[:gadgets]
    @gadget = Gadget.new
    @gadget.title = params[:title]
    @gadget.useful_for = params[:useful_for]
    @gadget.analysis_group = params[:analysis_group]
    @gadget.gadget_description = params[:gadget_description]
    @gadget.cost = params[:cost]
    @gadget.currency_id = params[:currency_id]
    @gadget.tool_aviable = params[:tool_aviable]
    @gadget.technology_used = params[:technology_used]
    @gadget.scientific_description = params[:scientific_description]
     if @gadget.save
      render json: Project::Writer::GadgetWriter.new.write_create(@gadget)
     else
     	render :json => "badresponce"
     end
  end

  def edit
   gadget = Gadget.find(params[:id])
   render json: Project::Writer::GadgetWriter.new.write_edit(gadget)
  end

  def update
    puts params[:gadget]
    @gadget = Gadget.find(params[:gadgets][:id])
    @gadget.title = params[:gadget][:title] 
    @gadget.useful_for = params[:useful_for]
    @gadget.analysis_group = params[:analysis_group]
    @gadget.gadget_description = params[:gadget_description]
    @gadget.cost = params[:cost]
    @gadget.currency_id = params[:currency_id]
    @gadget.tool_aviable = params[:tool_aviable]
    @gadget.technology_used = params[:technology_used]
    @gadget.scientific_description = params[:scientific_description]
     if @gadget.save
      render json: Project::Writer::GadgetWriter.new.write_update(@gadget)
     else
     	render :json => "bad responce"
     end
  end

  def destroy
  @gadget = Gadget.destroy(params[:id])
   render status: 200, json: '1'
   # rescue ActiveRecord::RecordInvalid => exception
   # render status: 403, json: exception.record.errors
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/gadgets_controller.rb
class GadgetsController < ApplicationController

   before_action :set_product, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!

  # GET /products
  # GET /products.json
  def index
   @search = Gadget.search(params[:q])
    # @gadgets = Gadget.all
    @gadgets = @search.result
  end

  # GET /products/1
  # GET /products/1.json
  def show 
    render :text => "saved successfully"
  end

  # GET /products/new
  def new
    @gadget = Gadget.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @gadget = Gadget.new(gadget_params)
    respond_to do |format|
      if @gadget.save
        format.html { redirect_to @gadget, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @gadget }
      else
        format.html { render action: 'new' }
        format.json { render json: @gadget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
     # authorize @product
    respond_to do |format|
      if @gadget.update(gadget_params)
        format.html { redirect_to @gadget, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @gadget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @gadget.destroy
    respond_to do |format|
      format.html { redirect_to gadgets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @gadget = Gadget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gadget_params
      params.require(:gadget).permit(:title,:useful_for,:analysis_group,:gadget_description,:company_name,:company_website,
        :cost,:currency_id,:tool_aviable,:technology_used,:scientific_description)
    end
end
 

app/controllers/homeone_controller.rb
class HomeoneController < ApplicationController
  def index
    # render :text => "testing helloone controller"
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
# before_action :authenticate_user!
	def index
   # render :text => "this is test controller"
   #@home = Gadget.all
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
# before_action :authenticate_admin!, :except => :create

 def new
    super
 end
def create
  self.resource = warden.authenticate!(auth_options)
    set_flash_message(:notice, :signed_in) if is_navigational_format?
    sign_in(resource_name, resource)
    if !session[:return_to].blank?
      redirect_to session[:return_to]
      session[:return_to] = nil
    else
        super
    end

end

def destroy
    super
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :set_user, only: [:show, :edit, :update, :destroy]
 before_action :authenticate_user!,:except =>:new
  # GET /products
  # GET /products.json
  def index
    @users = User.all
  end

  # GET /products/1
  # GET /products/1.json
  def show 
    render :text => "successfully created code"
  end

  # GET /products/new
  def new
    @user = User.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
       else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
     # authorize @product
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email,:password,:password_confirmation,:firstname,:lastname,:role)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gadgets_helper.rb
module GadgetsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/gadgets/_form.html.erb
	 
	<%= form_for @gadget ,class: "form-horizontal" do |f|%>
    <div class="container">
      <div class="col-md-10">
        <div class="row">
            <div class="col-md-9">
              <%= f.text_field :title, required: true, class: 'form-control', placeholder: 'Enter Title Here' %>
            </div>
            <div class="col-md-3">
             <%= link_to "Back", gadgets_path, class: 'btn btn-primary' %>
             <%= f.submit "Save", class: 'btn btn-primary' %>
            </div>
          </div>
        <hr/>
          <div class="col-md-8">
		          <div class="row">
		            <div class="form-group">
		              <label class="col-md-3 control-label">Name of the method/gadget</label>  
		               <div class="col-md-9">
		              <%= f.text_field :title, required: true, class: 'form-control' %>
		             </div>
		            </div>
		          </div><br>
		          <div class="row">
		            <div class="form-group">
		              <label class="col-md-3 control-label">Useful for</label>  
		               <div class="col-md-9">
		              <%= f.text_field :useful_for, required: true, class: 'form-control' %>
		             </div>
		            </div>
		          </div><br>
		          <div class="row">
		            <div class="form-group">
		              <label class="col-md-3 control-label">Gadget description</label>  
		               <div class="col-md-9">
		              <%= f.text_field :gadget_description, required: true, class: 'form-control' %>
		             </div>
		            </div>
		          </div><br>
		           <div class="row">
		            <div class="form-group">
		              <label class="col-md-3 control-label">Analysis group</label>  
		               <div class="col-md-9">
		              <%= f.text_field :analysis_group, required: true, class: 'form-control' %>
		             </div>
		            </div>
		          </div><br>

		           <div class="row">
		            <div class="form-group">
		              <label class="col-md-3 control-label">Company name</label>  
		               <div class="col-md-9">
		              <%= f.text_field :company_name, required: true, class: 'form-control' %>
		             </div>
		            </div>
		          </div><br>

		          <div class="row">
		            <div class="form-group">
		              <label class="col-md-3 control-label">Company website</label>  
		               <div class="col-md-9">
		              <%= f.text_field :company_website, required: true, class: 'form-control'%>
		             </div>
		            </div>
		          </div><br>
		          <div class="row">
		            <div class="form-group">
		              <label class="col-md-3 control-label">Currency</label> 
		              <div class="col-md-6">
		                <%= f.text_field :currency_id, required: true, class: 'form-control'%>
		              </div> 
		               <div class="col-md-3">
		              <%= f.collection_select :currency_id, Gadget::CURRENCY,
		              :to_s, :to_s,{:include_blank => false},{class: "form-control"}%>
		             </div>
		            </div>
		          </div><br>

              <div class="row">
                <label class="col-md-3 control-label">Tools for users</label>
                <div class="col-md-9">
                <%if @gadget.tool_aviable=="Yes" %>
							      <%= f.radio_button :tool_aviable, "yes",:checked => true,:id=>"first" %>
							       <label for="first">Aviable</label>
							       <%= f.radio_button :tool_aviable, "NO",:checked => false,:id=>"second" %>
							   <label for="second">Not aviable</label>
							  
							  <%elsif @gadget.tool_aviable="No"%>
                     <%= f.radio_button :tool_aviable, "yes",:checked => false,:id=>"first" %>
							       <label for="first">Aviable</label>
							       <%= f.radio_button :tool_aviable, "NO",:checked => true,:id=>"second" %>
							        <label for="first">Not aviable</label>
							  <%else%>
							  
							   <%= f.radio_button :tool_aviable, "yes",:checked => true,:id=>"first" %>
							      <label for="first">Aviable</label>
							       <%= f.radio_button :tool_aviable, "NO",:checked => false,:id=>"second" %>
							       <label for="first">Aviable</label>
							  <%end%>
							   
                </div>
              </div><br/>

              <div class="row">
		            <div class="form-group">
		              <label class="col-md-3 control-label">Technology used</label>  
		               <div class="col-md-9">
		              <%= f.text_field :technology_used, required: true, class: 'form-control'%>
		             </div>
		            </div>
		          </div><br>

		          <div class="row">
		            <div class="form-group">
		              <label class="col-md-3 control-label">Scientific reason</label>  
		               <div class="col-md-9">
		              <%= f.text_field :scientific_description, required: true, class: 'form-control'%>
		             </div>
		            </div>
		          </div><br>
              
              <div class="row col-md-offset-5"> 
	              <%= link_to "Back", gadgets_path, class: 'btn btn-primary' %>
	              <%= f.submit "Save", class: 'btn btn-primary' %>
              </div>

		          </div>
		          </div>

          </div>
     

	<%end%>

app/views/gadgets/edit.html.erb
<%= render 'form' %>

app/views/gadgets/index.html.erb
	  <div class="col-md-10 well">
      <p class="lead">Gadget inventory</p>
           <div class="row">
             <div class="col-md-12">
               <%= search_form_for @search do |f| %>
                  <div class="row">
		                <div class="form-group">
		                  <label class="col-md-1 control-label">Company name</label>  
		                  <div class="col-md-6">
		                  &nbsp;&nbsp;<%= f.text_field :company_name_start, required: true, class: 'form-control' %>
		                  </div>
		                </div>
		              </div><br>
		        <%= f.submit "search", class: 'btn' %>
               <%end%>
             </div>       

           </div>  
            <p class="lead">Listing products</p>
          <div class="row">
            <div class="col-md-8 col-md-offset-2">
              <table class="table table-striped table-hover">
                <thead>
                  <tr>
                    <th>Title</th>
                    <th>Useful_for</th>
                    <th>Company_name</th>
                    <th>Actions</th>
                  </tr>
                </thead>
                <tbody>
                  <% @gadgets.each do |gadget| %>
                    <tr>
                      <td><%= gadget.title%></td>
                      <td><%= gadget.useful_for%></td>
                      <td><%=gadget.company_name%></td>
                      <td><%= link_to 'Show', "#" %></td>
                      <td><%= link_to 'Edit',edit_gadget_path(gadget)%></td>
                      <td><%= link_to 'Destroy',gadget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    </tr>
                  <% end %>
                </tbody>
							</table>
            </div>
        </div>
        <br>
    </div>

  <div class="col-md-2">
    <%= link_to 'New Product',new_gadget_path,:class=>"btn btn-primary" %>
	</div>

app/views/gadgets/new.html.erb
<%=render 'form' %>

app/views/homeone/index.html.erb
<div ng-app="myApp">
<div ui-view="container"></div>
<div ui-view="showgadget"></div>
<div ui-view="newform"></div>
<div ui-view="deleteproduct"></div>
<div ui-view="editgadget"></div>
</div>

app/views/homes/index.html.erb
<div class="row">
	 <div class="col-md-2 sidebar-padding">
		 <div class="list-group">
		  <a href="#" class="list-group-item active">
		    Users</a>
		  <a href="#" class="list-group-item">Roles
		  </a>
		  <a href="#" class="list-group-item">Gadget inventory
		  </a>
		</div>
	</div>
  
	  <div class="col-md-10">
      <p class="lead">Gadget inventory</p>  
            <p class="lead">Listing products</p>
          <div class="row">
            <div class="col-md-8">
							<table class="table table-striped table-hover">
							  <thead>
							    <tr>
							      <th>Title</th>
							      <th>Name of the tool</th>
							      <th>Analysis group(s)</th>
							      <th>Actions</th>
							    </tr>
							  </thead>

							  <tbody>
							    <% [1,2].each do |product| %>
							      <tr>
							        <td>Ipad</td>
							        <td>Ipad 5s latest</td>
							        <td>Ipad</td>
							        <td><%= link_to 'Show', "#" %></td>
							        <td><%= link_to 'Edit',"#" %></td>
							        <td><%#= link_to 'Destroy' product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
							      </tr>
							      <tr>
							        <td>Ipad</td>
							        <td>Ipad 5s latest</td>
							        <td>Ipad</td>
							        <td><%= link_to 'Show', "#" %></td>
							        <td><%= link_to 'Edit',"#" %></td>
							        <td><%#= link_to 'Destroy' product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
							      </tr>
							    <% end %>
							  </tbody>
							</table>
            </div>
         </div>
      <br>
    </div>
<%= link_to 'New Product', new_home_path %>
	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-inverse">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Brand</a>
  </div>
  <div class="navbar-collapse collapse navbar-responsive-collapse">
    <ul class="nav navbar-nav">
      <li class="active"><a href="#">Active</a></li>
      <li><a href="#">Link</a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="#">Action</a></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>
          <li class="divider"></li>
          <li class="dropdown-header">Dropdown header</li>
          <li><a href="#">Separated link</a></li>
          <li><a href="#">One more separated link</a></li>
        </ul>
      </li>
    </ul>
    <form class="navbar-form navbar-left">
      <input class="form-control col-lg-8" placeholder="Search" type="text">
    </form>
    <ul class="nav navbar-nav navbar-right">
     <% if current_user %>
     <!-- <button type="button" class="btn btn-success">Logout</button> -->
     <%=link_to "Logout",destroy_user_session_path,:method =>:delete,:class =>"btn" %>
     <%end%>
    </ul>
  </div>
</div>
<div class="container">

 <div class="row">
  <div class="col-md-2 sidebar-padding">
    <% if current_user %>
     <div class="list-group">
      <a href="/admin/admins" class="list-group-item active">
        Users</a>
      <a href="/gadgets" class="list-group-item">Gadget inventory
      </a>
    </div>
    <%end%>
  </div>

 <%= yield %>
 </div>
</div>
</body>
</html>

app/views/users/_form.html.erb
	<div class="col-md-10">
	  <div class="col-md-9">
      <div class="well">
       <legend>User Registration form</legend>
      <div class="col-md-offset-1">

       <%= form_for @user ,class: "form-horizontal" do |f|%>
        
        <div class="row">
            <div class="form-group">
		              <label class="col-md-2 control-label">First name</label>  
		               <div class="col-md-6">
		              <%= f.text_field :firstname, required: true, class: 'form-control',place_holder: "Enter first name"%>
		             </div>
		            </div>
        </div><br/>
        
        <div class="row">
            <div class="form-group">
		              <label class="col-md-2 control-label">Last name</label>  
		               <div class="col-md-6">
		              <%= f.text_field :lastname, required: true, class: 'form-control'%>
		             </div>
		            </div>
        </div><br/>
        <div class="row">
            <div class="form-group">
		              <label class="col-md-2 control-label">Email</label>  
		               <div class="col-md-6">
		              <%= f.email_field :email, required: true, class: 'form-control'%>
		             </div>
		            </div>
        </div><br/>
        <div class="row">
            <div class="form-group">
		              <label class="col-md-2 control-label">Password</label>  
		               <div class="col-md-6">
		              <%= f.password_field :password, required: true, class: 'form-control'%>
		             </div>
		            </div>
        </div><br/>

			        <div class="row">
			            <div class="form-group">
					              <label class="col-md-2 control-label">Password confirmation</label>  
					               <div class="col-md-6">
					              <%= f.password_field :password_confirmation, required: true, class: 'form-control'%>
					             </div>
					            </div>
			        </div><br/>

			        <div class="row">
			            <div class="form-group">
					              <label class="col-md-2 control-label">Role</label>  
					               <div class="col-md-6">
					             <%= f.collection_select :role, User::ROLES,
					              :to_s, :to_s,{:include_blank => false},{class: "form-control"}%>
					             </div>
					            </div>
			        </div><br/>

					      <div class="row col-md-offset-3">
					        <%= link_to "Back", users_path, class: 'btn btn-primary' %>
					        <%= f.submit "Save", class: 'btn btn-default' %>
					      </div>

			       <%end%>
    </div>
    </div>
    </div>
	</div>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
	  <div class="col-md-8"> 
	  <br/>
            <p class="lead">Listing Users</p>
          <div class="row">
            <div class="col-md-7">
							<table class="table table-striped table-hover">
							  <thead>
							    <tr>
							      <th>Email</th>
							      <th>Firstname</th>
							      <th>Lastname</th>
							      <th>Role</th>
							      <th>Actions</th>
							    </tr>
							  </thead>

							  <tbody>
							    <% @users.each do |user| %>
							      <tr>
							        <td><%= user.email %></td>
							        <td><%= user.firstname %></td>
							        <td><%= user.lastname %></td>
							        <td><%= user.role%></td>
							        <td><%= link_to 'Show', "#" %></td>
							        <td><%= link_to 'Edit',edit_user_path(user)%></td>
							        <td><%= link_to 'Destroy',user,:method =>:delete %></td>
							      </tr>
							    <% end %>
							  </tbody>
							</table>
            </div>
         </div>
      <br>
    </div>

  <div class="col-md-2">
    <%= link_to 'New Admin',new_user_path,:class=>"btn btn-primary",style: "float :pull-left"%>
     <!-- <button type="submit" >NewProduct</button> -->
</div>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<div class="col-md-8">




</div>